- name: Configuration mysql Server
  hosts: mysql
  become: yes
  tasks:
    - name: Install mysql
      package:
        name: mysql-server
        state: present

    - name: Start and enabled service
      service:
        state: started
        enabled: yes
        
    - name: Setup root ansible_password
      command: mysql_secure_installation --set-root-pass RoboShop@1
