[local]
localhost

[mongodb]
mongodb.anjidevops.online

[frontend]
frontend.anjidevops.online

[redis]
redis.anjidevops.online

[rabbitmq]
rabbitmq.anjidevops.online

[user]
user.anjidevops.online

[mysql]
mysql.anjidevops.online

[cart]
cart.anjidevops.online

[catalogue]
catalogue.anjidevops.online

[shipping]
shipping.anjidevops.online


[payment]
payment.anjidevops.online

